package com.bookstore.entity;
// Generated May 5, 2019, 11:32:51 PM by Hibernate Tools 5.4.2.Final

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private OrderDetailsId id;
	private Book book;
	private BookOrder bookOrder;
	private int quantity;
	private float subTotal;

	public OrderDetails() {
	}

	public OrderDetails(OrderDetailsId id, Book book, BookOrder bookOrder, int quantity, float subTotal) {
		this.id = id;
		this.book = book;
		this.bookOrder = bookOrder;
		this.quantity = quantity;
		this.subTotal = subTotal;
	}

	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public BookOrder getBookOrder() {
		return this.bookOrder;
	}

	public void setBookOrder(BookOrder bookOrder) {
		this.bookOrder = bookOrder;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}

}
